language: node_js
node_js:
  - "0.12"
  - "4"
  - "5"
env:
  - CXX=g++-4.8
addons:
  sauce_connect: true
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
script: "npm run travis"